version: '3.3'

services:
  api:
    build: ./cyberspectortest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cyberspectortest:/app
    ports:
      - "8000:8000"

  frontend:
    build: ./cyberspectortest-frontend
    dockerfile: Dockerfile
    volumes:
      - ./cyberspectortest-frontend:/app 
    ports:
      - "8080:8080"
    depends_on:
      - api