# Generated by Django 5.1.1 on 2024-09-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csirts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csirt',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='csirt',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csirt',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csirt',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='csirt',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
